[server]
host = "127.0.0.1"
dns = "localhost"
http_port = 21000
game_port = 23301

[paths]
data_dir = "./data"
excel_data = "./data/excel2json"
static_data = "./data/static"

[database]
path = "./db/sonetto.db"
